dist: debian


language: python


branches:
  only:
    - master

matrix:
  include:
    - python: 3.8
      env: TOXENV=black

    - python: 3.5
      env: TOXENV=py35,codecov
    - python: 3.6
      env: TOXENV=py36,codecov
    - python: 3.7
      env: TOXENV=py37,codecov
    - python: 3.8
      env: TOXENV=py38,codecov
    - python: pypy3
      env: TOXENV=pypy3,codecov

install:
  - pip install tox


script:
  - tox
